# Generated by Django 5.1.3 on 2025-01-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="resume",
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
