# Generated by Django 5.1.3 on 2025-01-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_image_alter_user_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
