name: Unit Tests (CI/CD)

on:
  push:
    branches:
      - master  # Run on pushes to the main branch
  pull_request:
    branches:
      - '**'  # Run on pull requests to any branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: JobScout.settings
      SECRET_KEY: dummy_secret_key
      DEBUG: 1

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up environment variables from .env
      - name: Add .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      # Step 5: Run migrations
      - name: Run migrations
        run: python manage.py makemigrations users jobs job_applications upload && python manage.py migrate

      # Step 6: Run tests
#      - name: Run pytest
#        run: pytest --strict-markers --cov=. --cov-report=xml --cov-report=html

