name: Secrets/Black

on:
  push:
    branches:
      - master  # Run on pushes to the main branch
  pull_request:
    branches:
      - '**'  # Run on pull requests to any branch

jobs:
  secrets-scan:
    name: Check for Secrets
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run Gitleaks to Scan for Secrets
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v1
        with:
          config: ""
          verbose: true
          fail: true  # Fail the workflow if secrets are found

      # Optional Step 3: Output Report if Secrets Found
      - name: Save Report
        if: failure()  # Only run if secrets are found
        run: |
          mkdir -p reports
          mv gitleaks.log reports/secret_scan_report.log
        continue-on-error: false

        # Step 4: Install Black
      - name: Install Black
        run: |
           python -m pip install --upgrade pip
           pip install black

        # Step 5: Run Black in check mode
      - name: Check formatting with Black
        run: black --check .
